// constants/coverTemplates.ts
export const COVER_TEMPLATES: CoverPageTemplate[] = [
  {
    key: 'legal_cover_v1',
    name: 'Legal Cover – Default',
    description: 'Professional legal document cover page',
    page: {
      size: 'A4',
      margin: 20,
      orientation: 'portrait',
    },
    fields: [
      {
        name: 'title',
        x: 105,
        y: 60,
        font: 'Times-Bold',
        size: 24,
        align: 'center',
        bold: true,
      },
      {
        name: 'case_number',
        x: 105,
        y: 85,
        font: 'Times',
        size: 14,
        align: 'center',
      },
      {
        name: 'court_name',
        x: 105,
        y: 105,
        font: 'Times',
        size: 12,
        align: 'center',
      },
      {
        name: 'prepared_for',
        x: 30,
        y: 140,
        font: 'Times-Bold',
        size: 11,
        align: 'left',
        bold: true,
      },
      {
        name: 'prepared_for_value',
        x: 30,
        y: 150,
        font: 'Times',
        size: 11,
        align: 'left',
      },
      {
        name: 'prepared_by',
        x: 30,
        y: 170,
        font: 'Times-Bold',
        size: 11,
        align: 'left',
        bold: true,
      },
      {
        name: 'prepared_by_value',
        x: 30,
        y: 180,
        font: 'Times',
        size: 11,
        align: 'left',
      },
      {
        name: 'date',
        x: 30,
        y: 200,
        font: 'Times-Bold',
        size: 11,
        align: 'left',
        bold: true,
      },
      {
        name: 'date_value',
        x: 30,
        y: 210,
        font: 'Times',
        size: 11,
        align: 'left',
      },
    ],
  },
  {
    key: 'simple_cover_v1',
    name: 'Simple Cover',
    description: 'Minimalist cover page',
    page: {
      size: 'A4',
      margin: 20,
      orientation: 'portrait',
    },
    fields: [
      {
        name: 'title',
        x: 105,
        y: 100,
        font: 'Helvetica-Bold',
        size: 28,
        align: 'center',
        bold: true,
      },
      {
        name: 'subtitle',
        x: 105,
        y: 130,
        font: 'Helvetica',
        size: 14,
        align: 'center',
      },
      {
        name: 'date_value',
        x: 105,
        y: 260,
        font: 'Helvetica',
        size: 12,
        align: 'center',
      },
    ],
  },
  {
    key: 'court_submission_v1',
    name: 'Court Submission',
    description: 'Formal court document cover',
    page: {
      size: 'A4',
      margin: 20,
      orientation: 'portrait',
    },
    fields: [
      {
        name: 'court_header',
        x: 105,
        y: 40,
        font: 'Times-Bold',
        size: 16,
        align: 'center',
        bold: true,
      },
      {
        name: 'case_number',
        x: 105,
        y: 60,
        font: 'Times',
        size: 14,
        align: 'center',
      },
      {
        name: 'case_title',
        x: 105,
        y: 90,
        font: 'Times-Bold',
        size: 18,
        align: 'center',
        bold: true,
      },
      {
        name: 'document_type',
        x: 105,
        y: 130,
        font: 'Times',
        size: 14,
        align: 'center',
      },
      {
        name: 'filed_by',
        x: 30,
        y: 170,
        font: 'Times',
        size: 11,
        align: 'left',
      },
      {
        name: 'counsel',
        x: 30,
        y: 190,
        font: 'Times',
        size: 11,
        align: 'left',
      },
      {
        name: 'date_value',
        x: 105,
        y: 260,
        font: 'Times',
        size: 11,
        align: 'center',
      },
    ],
  },
];

// Default field values for each template
export const DEFAULT_COVER_VALUES: Record<string, Record<string, string>> = {
  legal_cover_v1: {
    title: 'CASE FILE',
    case_number: 'Case No: ',
    court_name: '',
    prepared_for: 'Prepared For:',
    prepared_for_value: '',
    prepared_by: 'Prepared By:',
    prepared_by_value: '',
    date: 'Date:',
    date_value: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
  },
  simple_cover_v1: {
    title: 'Document Bundle',
    subtitle: '',
    date_value: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
  },
  court_submission_v1: {
    court_header: 'IN THE SUPREME COURT',
    case_number: 'Case No: ',
    case_title: '',
    document_type: 'CASE BUNDLE',
    filed_by: 'Filed by: ',
    counsel: 'Counsel: ',
    date_value: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
  },
};
